services:
  - type: web
    name: faidakomori
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SITE_URL
        value: https://faidakomori.onrender.com
      - key: EMAIL_USER
        value: athoumaniyas@gmail.com
      - key: ADMIN_EMAIL
        value: athoumaniyas@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
